name: Publish to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download HTML artifact from last build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download \
            --repo ${{ github.repository }} \
            --name ech-standard-output \
            --dir _site \
            $(gh run list \
              --repo ${{ github.repository }} \
              --workflow build.yml \
              --status success \
              --limit 1 \
              --json databaseId \
              --jq '.[0].databaseId')

      - name: Rename HTML to index.html
        run: mv _site/standard.html _site/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
